name: Vue build test

# master 브랜치로의 PR이 있으면 workflow를 실행함 
# paths 설정이 있으므로 -> my-garden-fe의 하위 파일들이 변경된 경우에만 실행됨
on:
  pull_request:
    branches:
      - master
    paths:
      - my-garden-fe/**

# 환경 변수 정의
env:
  NODE_VERSION: 20 # 본인이 사용하는 node 버전에 맞춰서 정의해주세요!

jobs:
  front-build:
    runs-on: ubuntu-latest

    # steps에 대한 기본 작업 디렉토리 설정
    defaults:
      run:
        working-directory: ./my-garden-fe

    steps:
      # 저장소 코드를 체크아웃합니다. (PR 올린 코드를 가져오는 행위)
      - uses: actions/checkout@v4

      # Node.js 환경 설정
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }} # 지정된 Node.js 버전 사용
          cache: npm # setup-node 의 캐시 기능을 사용함 (저는 npm을 사용하므로 npm을 썼습니다. -> 본인의 세팅에 맞춰서 변경해야 합니다.)
          cache-dependency-path: my-garden-fe/package-lock.json # 캐시 기능을 사용할 때 캐시의 기준이 될 파일을 지정

      - name: Install Dependencies
        run: npm install

      - name: Build with npm
        run: npm run build
