name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Create env file
        run: |
          echo "VITE_APP_API_URL=${{ secrets.VITE_APP_API_URL }}" > .env.production
          echo "NODE_ENV=production" >> .env.production

      - name: Install dependencies
        run: npm ci

      # ✅ 빌드 실행
      - name: Build with Debugging
        run: npm run build --verbose
        env:
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}

      # ✅ dist 폴더가 정상적으로 생성되었는지 확인
      - name: Debug Build Output
        run: ls -la ./dist || echo "dist folder not found!"

      - name: Verify dist folder
        run: |
          if [ -d "./dist" ]; then
            echo "dist directory exists."
          else
            echo "dist directory does not exist!"
            exit 1
          fi

      - name: Add CNAME file
        run: echo 'blu2print.site' > ./dist/CNAME

      # ✅ 배포 (업로드 없이 바로 dist 폴더 사용)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
          path: ./dist  # ✅ 빌드된 dist 폴더 직접 배포
